version: '3'

tasks:
  build:
    desc: Build entire Conqueror solution
    cmds:
      - dotnet build Conqueror.sln {{.CLI_ARGS}}

  test:
    desc: Run all tests in Conqueror solution
    cmds:
      - dotnet test Conqueror.sln {{.CLI_ARGS}}
