<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <Import Project="../../.targets/common.targets" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Conqueror.Transport.Http.Client" Version="$(ConquerorVersion)" Condition="$(ShouldReferencePackage)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.8" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/transports/http/Conqueror.Transport.Http.Client/Conqueror.Transport.Http.Client.csproj" Condition="$(ShouldReferenceProject)" />
    <ProjectReference Include="../Examples.BlazorWebAssembly.Contracts/Examples.BlazorWebAssembly.Contracts.csproj" />
    <ProjectReference Include="../Examples.BlazorWebAssembly.SharedMiddlewares/Examples.BlazorWebAssembly.SharedMiddlewares.csproj" />

    <!-- only required when using project references; when using a package reference the source generator is included in the abstractions package -->
    <ProjectReference Include="../../../src/Conqueror.SourceGenerators/Conqueror.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Condition="$(ShouldReferenceProject) == true" />
  </ItemGroup>

</Project>
