namespace Conqueror;

/// <summary>
///     This interface does not need to be added manually to user code. It is
///     generated by the source generator and is used by Conqueror APIs to infer
///     the types.
/// </summary>
/// <typeparam name="TIterator">the iterator type</typeparam>
/// <typeparam name="TItem">the item type</typeparam>
public interface IIterator<TIterator, TItem>
    where TIterator : class, IIterator<TIterator, TItem>
{
    /// <summary>
    ///     This is an internal helper property used by Conqueror to work around the need for
    ///     reflection. Implementations of the property should only be created by the source
    ///     generator.
    /// </summary>
    static abstract IIteratorHandlerTypesInjector CoreTypesInjector { get; }

    /// <summary>
    ///     Some transports must be able to construct an instance of this iterator
    ///     if it has no properties, but since this is only known to the actual
    ///     type, we cannot use the generic type constraint 'new()'. Instead, we
    ///     generate an empty instance in the source generator if the iterator type
    ///     does not have any properties.
    /// </summary>
    static abstract TIterator? EmptyInstance { get; }

    /// <summary>
    ///     The <see cref="System.Text.Json.Serialization.JsonSerializerContext" />
    ///     to use by default for any operation that needs to JSON-serialize or
    ///     deserialize an iterator of type <typeparamref name="TIterator" /> or an item of
    ///     type <typeparamref name="TItem" />.<br />
    ///     <br />
    ///     When this is <see langword="null" /> and dynamic code generation is enabled (i.e.
    ///     the app is not running with AOT) then the serialization will use a default
    ///     context depending on where it is being used.
    /// </summary>
    static virtual JsonSerializerContext? JsonSerializerContext => null;

    static abstract IEnumerable<ConstructorInfo> PublicConstructors { get; }

    static abstract IEnumerable<PropertyInfo> PublicProperties { get; }

    static abstract IAsyncEnumerable<TItem> InvokeHandler<TIHandler>(
        TIHandler handler,
        TIterator iterator,
        CancellationToken cancellationToken
    )
        where TIHandler : class, IIteratorHandler<TIterator, TItem, TIHandler>;
}

/// <summary>
///     This helper class is only used for enhanced type inference.
/// </summary>
/// <typeparam name="TIterator">the iterator type</typeparam>
/// <typeparam name="TItem">the item type</typeparam>
/// <typeparam name="TIHandler">the handler interface type</typeparam>
public sealed class IteratorTypes<TIterator, TItem, TIHandler>
    where TIterator : class, IIterator<TIterator, TItem>
    where TIHandler : class, IIteratorHandler<TIterator, TItem, TIHandler>
{
    [SuppressMessage(
        "Usage",
        "MA0015:Specify the parameter name in ArgumentException",
        Justification = $"false positive, {nameof(TIHandler)} is a generic type parameter"
    )]
    public IteratorTypes()
    {
        if (
            !typeof(TIHandler).IsInterface
            || !string.Equals(typeof(TIHandler).Name, "IHandler", StringComparison.Ordinal)
        )
        {
            throw new ArgumentException(
                $"expected iterator handler interface for iterator type '{typeof(TIterator)}', but got '{typeof(TIHandler)}'",
                nameof(TIHandler)
            );
        }
    }
}
