version: '3'

tasks:
  build:
    desc: Build all http transport projects
    cmds:
      - dotnet build Conqueror.Transport.Http.sln {{.CLI_ARGS}}

  test:
    desc: Run http transport tests
    cmds:
      - dotnet test Conqueror.Transport.Http.sln {{.CLI_ARGS}}

  fmt:
    desc: Format files with csharpier
    cmds:
      - dotnet csharpier format . {{.CLI_ARGS}}

  fmt:check:
    desc: Check formatting with csharpier (for CI)
    cmds:
      - dotnet csharpier check . {{.CLI_ARGS}}
