<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../.targets/analyzers.targets" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Conqueror/Conqueror.csproj" />
    <ProjectReference
      Include="../Conqueror.SourceGenerators/Conqueror.SourceGenerators.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
    <ProjectReference Include="../middlewares/authorization/Conqueror.Middleware.Authorization/Conqueror.Middleware.Authorization.csproj" />
    <ProjectReference Include="../middlewares/logging/Conqueror.Middleware.Logging/Conqueror.Middleware.Logging.csproj" />
    <ProjectReference Include="../transports/http/Conqueror.Transport.Http.Client/Conqueror.Transport.Http.Client.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TrimmerRootAssembly>Conqueror</TrimmerRootAssembly>
    <TrimmerRootAssembly>Conqueror.Middleware.Authorization</TrimmerRootAssembly>
    <TrimmerRootAssembly>Conqueror.Middleware.Logging</TrimmerRootAssembly>
    <TrimmerRootAssembly>Conqueror.Transport.Http.Client</TrimmerRootAssembly>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <!-- Exclude the output of source generators from the compilation -->
    <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
  </ItemGroup>
  <Target
    Name="CleanSourceGeneratedFiles"
    BeforeTargets="BeforeCompile"
    Inputs="@(Compile);@(AdditionalFiles)"
    Outputs="Generated/.timestamp"
  >
    <RemoveDir Directories="Generated" />
    <MakeDir Directories="Generated" />
    <Touch Files="Generated/.timestamp" AlwaysCreate="true" />
  </Target>
</Project>
