namespace Conqueror.SourceGenerators.Util;

using System.Diagnostics.CodeAnalysis;

internal static class StringBuilderExtensions
{
    public static StringBuilder AppendSingleIndent(this StringBuilder sb) => sb.Append("    ");

    public static StringBuilder AppendIndentation(this StringBuilder sb, Indentation indentation)
    {
        for (var i = 0; i < indentation.Level; i++)
        {
            _ = sb.AppendSingleIndent();
        }

        return sb;
    }

    public static StringBuilder AppendLineWithIndentation(this StringBuilder sb, Indentation indentation) =>
        sb.AppendLine().AppendIndentation(indentation);

    public static IDisposable AppendBlock(this StringBuilder sb, Indentation indentation, bool addNewLineAtEnd = true)
    {
        _ = sb.AppendIndentation(indentation).Append('{').AppendLine();

        var indentDisposable = indentation.Indent();

        return new AnonymousDisposable(() =>
        {
            indentDisposable.Dispose();

            _ = sb.AppendIndentation(indentation).Append('}');

            if (addNewLineAtEnd)
            {
                _ = sb.AppendLine();
            }
        });
    }

    public static IDisposable AppendNamespace(this StringBuilder sb, Indentation indentation, string namespaceName)
    {
        return sb.AppendIndentation(indentation)
            .Append("namespace ")
            .AppendLine(namespaceName)
            .AppendBlock(indentation);
    }

    public static StringBuilder AppendGeneratedCodeAttribute(
        this StringBuilder sb,
        Indentation indentation,
        string generatorName,
        string generatorVersion
    )
    {
        return sb.AppendIndentation(indentation)
            .AppendLine(
                $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"{generatorName}\", \"{generatorVersion}\")]"
            );
    }

    public static StringBuilder AppendEditorBrowsableNeverAttribute(this StringBuilder sb, Indentation indentation)
    {
        return sb.AppendIndentation(indentation)
            .AppendLine(
                "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]"
            );
    }

    public static StringBuilder AppendFileHeader(this StringBuilder sb)
    {
        const string header = """
                              //------------------------------------------------------------------------------
                              // <auto-generated>
                              //     This code was generated by a Conqueror source generator.
                              //
                              //     Changes to this file may cause incorrect behavior and will be lost if
                              //     the code is regenerated.
                              // </auto-generated>
                              //------------------------------------------------------------------------------

                              #nullable enable annotations
                              #nullable disable warnings

                              #pragma warning disable

                              """;

        return sb.AppendLine(header);
    }

    [SuppressMessage(
        "Reliability",
        "CA2000:Dispose objects before losing scope",
        Justification = "false positive, aggregate disposable is returned"
    )]
    public static IDisposable AppendParentClasses(
        this StringBuilder sb,
        Indentation indentation,
        EquatableArray<ParentClass> parentClasses
    )
    {
        var aggregateDisposable = new AggregateDisposable();

        foreach (var parentClass in parentClasses)
        {
            aggregateDisposable.Add(sb.AppendParentClass(indentation, parentClass));
        }

        return aggregateDisposable;
    }

    private static IDisposable AppendParentClass(
        this StringBuilder sb,
        Indentation indentation,
        ParentClass parentClass
    )
    {
        return sb.AppendIndentation(indentation)
            .Append("partial ")
            .Append(parentClass.Keyword)
            .Append(value: ' ')
            .AppendLine(parentClass.Name)
            .AppendBlock(indentation);
    }
}
