version: '3'

tasks:
  build:
    desc: Build all middleware projects
    cmds:
      - dotnet build Middlewares.sln {{.CLI_ARGS}}

  test:
    desc: Run all middleware tests
    cmds:
      - dotnet test Middlewares.sln {{.CLI_ARGS}}
