using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Conqueror.SourceGenerators.Messaging;

[SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "this is common for working with string builders")]
public static class MessageAbstractionsGenerationHelper
{
    private const string Header = @"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Conqueror.SourceGenerators source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable";

    public static (string Content, string FileName) GenerateMessageTypes(in MessageTypeToGenerate typesToGenerate)
    {
        var sb = new StringBuilder();
        sb.AppendLine(Header);

        GenerateType(sb, in typesToGenerate.MessageTypeDescriptor, in typesToGenerate.ResponseTypeDescriptor);

        var content = sb.ToString();
        sb.Clear();

        var filename = sb
                       .Append(typesToGenerate.MessageTypeDescriptor.FullyQualifiedName)
                       .Append("_MessageTypes.g.cs")
                       .Replace('<', '_')
                       .Replace('>', '_')
                       .Replace(',', '.')
                       .Replace(' ', '_')
                       .ToString();

        return new(content, filename);
    }

    [SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1012:Opening braces should be spaced correctly", Justification = "false positive")]
    [SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1013:Closing braces should be spaced correctly", Justification = "false positive")]
    private static void GenerateType(StringBuilder sb, in TypeDescriptor messageTypeDescriptor, in TypeDescriptor? responseTypeDescriptor)
    {
        var messageTypeName = messageTypeDescriptor.Name;
        var responseTypeName = responseTypeDescriptor?.Name ?? "UnitMessageResponse";

        sb.Append("""

                  using Conqueror;

                  """);

        if (!string.IsNullOrEmpty(messageTypeDescriptor.Namespace))
        {
            sb.Append("""

                      namespace 
                      """)
              .Append(messageTypeDescriptor.Namespace)
              .Append("""

                      {
                      """);
        }

        var parentsCount = 0;
        var parentClass = messageTypeDescriptor.ParentClass;

        // TODO: proper indentation
        while (parentClass is not null)
        {
            sb.Append("\n    partial ")
              .Append(parentClass.Keyword) // e.g. class/struct/record
              .Append(' ')
              .Append(parentClass.Name) // e.g. Outer/Generic<T>
              .Append(' ')
              .Append(parentClass.Constraints) // e.g. where T: new()
              .AppendLine("""
                          
                              {
                          """);

            parentsCount += 1;
            parentClass = parentClass.Child;
        }

        var fullyQualifiedName = $"global::{messageTypeDescriptor.FullyQualifiedName}";

        sb.Append("""
                  
                      /// <summary>
                      /// Message Types for <see cref="
                  """)
          .Append(fullyQualifiedName)

          // TODO: move the attribute to the nested types to prevent issues with duplicate attributes
          .Append("""
                  " />
                      /// </summary>
                      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Conqueror.SourceGenerators.Messaging.MessageAbstractionsGenerator", "
                  """)
          .Append(Constants.Version)
          .Append("""
                  ")]
                      
                  """)
          .Append("partial ")
          .Append(messageTypeDescriptor.IsRecord ? "record " : "class ")
          .Append(messageTypeDescriptor.Name)
          .Append(" : IMessageTypes<")
          .Append(messageTypeDescriptor.Name)
          .Append(", ")
          .Append(responseTypeDescriptor?.Name ?? "UnitMessageResponse")
          .Append(">")
          .Append("""
                  
                      {
                  """);

        // TODO: handle response type in different namespace
        if (responseTypeDescriptor is not null)
        {
            // TODO: improve performance by not using templated strings
            sb.Append($$$"""
                         
                                  public interface IHandler : IGeneratedMessageHandler<{{{messageTypeName}}}, {{{responseTypeName}}}, IHandler, IHandler.Adapter, IPipeline, IPipeline.Adapter>
                                  {
                                      [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                      public sealed class Adapter : GeneratedMessageHandlerAdapter<{{{messageTypeName}}}, {{{responseTypeName}}}>, IHandler;
                                  }
                                  
                                  public interface IPipeline : IMessagePipeline<{{{messageTypeName}}}, {{{responseTypeName}}}>
                                  {
                                      [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                      public sealed class Adapter : GeneratedMessagePipelineAdapter<{{{messageTypeName}}}, {{{responseTypeName}}}>, IPipeline;
                                  }
                         """);
        }
        else
        {
            // TODO: improve performance by not using templated strings
            sb.Append($$$"""
                         
                                  public interface IHandler : IGeneratedMessageHandler<{{{messageTypeName}}}, IHandler, IHandler.Adapter, IPipeline, IPipeline.Adapter>
                                  {
                                      [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                      public sealed class Adapter : GeneratedMessageHandlerAdapter<{{{messageTypeName}}}>, IHandler;
                                  }
                                  
                                  public interface IPipeline : IMessagePipeline<{{{messageTypeName}}}, UnitMessageResponse>
                                  {
                                      [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                      public sealed class Adapter : GeneratedMessagePipelineAdapter<{{{messageTypeName}}}, UnitMessageResponse>, IPipeline;
                                  }
                         """);
        }

        if (!messageTypeDescriptor.HasProperties)
        {
            sb.Append($$$"""
                         
                         
                                 [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                 static {{{messageTypeName}}} IMessageTypes<{{{messageTypeName}}}, {{{responseTypeName}}}>.EmptyInstance => new();
                         """);
        }
        else
        {
            sb.Append($$$"""
                         
                         
                                 [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                                 static {{{messageTypeName}}}? IMessageTypes<{{{messageTypeName}}}, {{{responseTypeName}}}>.EmptyInstance => null;
                         """);
        }

        sb.Append($$$"""
                     
                     
                             [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
                             static global::System.Collections.Generic.IReadOnlyCollection<IMessageTypesInjector> global::Conqueror.IMessage<{{{responseTypeName}}}>.TypeInjectors
                                 => global::Conqueror.IMessageTypesInjector.GetTypeInjectorsForMessageType<{{{messageTypeName}}}>();
                     """);

        sb.Append("""
                  
                      }
                  """);

        for (var i = 0; i < parentsCount; i += 1)
        {
            sb.Append("""
                      
                          }
                      """);
        }

        if (!string.IsNullOrEmpty(messageTypeDescriptor.Namespace))
        {
            sb.Append("""

                      }

                      """);
        }
    }
}
