version: '3'

vars:
  SOLUTION_FILE: Conqueror.Middleware.Authorization.sln
  DESC_PREFIX: authorization middleware

includes:
  base:
    taskfile: ../../Taskfile.base.yml
    dir: .
    flatten: true
