global using System.Collections.Concurrent;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Net.ServerSentEvents;
global using System.Net.WebSockets;
global using System.Text;
global using Conqueror;
global using static Conqueror.ConquerorTransportHttpConstants;
global using Conqueror.Signalling.Sse;
global using Conqueror.Signalling.WebSockets;
global using Conqueror.Transport.Http.Client.Messaging;
global using Conqueror.Transport.Http.Client.Signalling.Sse;
global using Conqueror.Transport.Http.Client.Signalling.WebSockets;
global using Conqueror.Transport.Http.Client.WebSockets;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
