version: '3'

tasks:
  build:
    desc: Build recipe projects
    cmds:
      - dotnet build Conqueror.Recipes.Signalling.TestingHandlers.sln {{.CLI_ARGS}}

  test:
    desc: Run recipe tests
    cmds:
      - dotnet test Conqueror.Recipes.Signalling.TestingHandlers.sln {{.CLI_ARGS}}
