version: '3'

tasks:
  build:
    desc: Build recipe projects
    cmds:
      - dotnet build Conqueror.Recipes.Messaging.CleanArchitecture.sln {{.CLI_ARGS}}

  test:
    desc: Run recipe tests
    cmds:
      - dotnet test Conqueror.Recipes.Messaging.CleanArchitecture.sln {{.CLI_ARGS}}

  run:completed:
    desc: Run completed recipe web API
    cmds:
      - dotnet run --project .completed/Conqueror.Recipes.Messaging.CleanArchitecture.EntryPoint.WebApi -- {{.CLI_ARGS}}
