<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../.targets/lib.targets" />
  <PropertyGroup>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <!-- for NuGet -->
  <PropertyGroup>
    <Description>Part of the Conqueror library set. Communicate with messages, signals, and iterators via the file system. NOT INTENDED FOR PRODUCTION USAGE.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../core/Conqueror/Conqueror.csproj" />
    <ProjectReference Include="../Conqueror.Transport.FileSystem.Abstractions/Conqueror.Transport.FileSystem.Abstractions.csproj" />
  </ItemGroup>
</Project>
