version: '3'

tasks:
  build:
    desc: Build all core src projects (excluding middlewares, transports, recipes)
    cmds:
      - dotnet build Core.sln {{.CLI_ARGS}}

  test:
    desc: Run all core src tests (excluding middlewares, transports, recipes)
    cmds:
      - dotnet test Core.sln {{.CLI_ARGS}}

  test:generators:
    desc: Run all generator tests
    cmds:
      - dotnet test Conqueror.SourceGenerators.Tests {{.CLI_ARGS}}

  fmt:
    desc: Format files with csharpier
    cmds:
      - dotnet csharpier format . {{.CLI_ARGS}}

  fmt:check:
    desc: Check formatting with csharpier (for CI)
    cmds:
      - dotnet csharpier check . {{.CLI_ARGS}}
