namespace Quickstart;

using System.ComponentModel.DataAnnotations;
using Conqueror;

// The handler type is also enhanced by the Conqueror source generator, so it must be partial
internal sealed partial class IncrementCounterByAmountHandler(
        CountersRepository repository,
        ISignalPublishers publishers
    )
    // This interface (among other things) is generated by a source generator
    : IncrementCounterByAmount.IHandler
{
    // Configure a pipeline of middlewares which is executed for every message
    public static void ConfigurePipeline(IncrementCounterByAmount.IPipeline pipeline) =>
        pipeline
            // Conqueror ships with a handful of useful middleware packages
            // for common cross-cutting concerns like logging and authorization
            .UseLogging()
            // Pipelines can have inline middlewares for ad-hoc logic (or you can
            // build a full-fledged middleware; see the recipes for more details)
            .Use(ctx =>
            {
                // Perform a simple data annotation validation (in a real application you would
                // likely use a more powerful validation library like FluentValidation)
                Validator.ValidateObject(
                    ctx.Message,
                    new(ctx.Message),
                    validateAllProperties: true
                );

                // The middleware has access to the message with its proper type (i.e. the
                // compiler knows that `ctx.Message` is of type `IncrementCounterByAmount`),
                // so you could also write the validation directly like this:
                if (ctx.Message.IncrementBy <= 0)
                {
                    throw new ValidationException(
                        $"increment amount must be positive, but was {ctx.Message.IncrementBy}"
                    );
                }

                return ctx.Next(ctx.Message, ctx.CancellationToken);
            })
            // The `Use...` methods add middlewares to the pipeline, and afterward they can be
            // configured further, which is useful for extracting common configuration into a
            // shared method and then configure it per handler, e.g. like this:
            // `pipeline.UseDefault().WithIndentedJsonPayloadLogFormatting()`
            .ConfigureLogging(c =>
                c.MessagePayloadLoggingStrategy = PayloadLoggingStrategy.IndentedJson
            );

    public async Task<CounterIncrementedResponse> Handle(
        IncrementCounterByAmount message,
        CancellationToken cancellationToken = default
    )
    {
        var newValue = await repository.AddOrIncrementCounter(
            message.CounterName,
            message.IncrementBy
        );

        // `ISignalPublishers` is a factory to get a publisher for a signal type. The
        // `CounterIncremented.T` property is generated by the source generator and is used for
        // type inference. The 'For' method returns a `CounterIncremented.IHandler` (which is a
        // proxy used to publish the signal)
        await publishers
            .For(CounterIncremented.T)
            // When publishing a signal (or sending a message, etc.), you can also
            // specify a pipeline, which is executed before the transport is called.
            // And when the transport delivers the payload, the handler's own pipeline
            // is executed as well
            .WithPipeline(p => p.UseLogging())
            // The 'Handle' method is unique for each `IHandler`. This means that your
            // IDE's "Go to Implementation" feature will show all signal handlers for
            // this signal, making it simple to find all the places in your code where
            // a signal is used
            .Handle(new(message.CounterName, newValue, message.IncrementBy), cancellationToken);

        // You can also customize the transport which is used to publish the signal, for example,
        // to publish it via HTTP server-sent events. Note that it is also possible to do publish
        // to multiple transports at the same time using `b.UseAggregate()`; the details for this
        // can be found in the recipes
        await publishers
            .For(CounterIncremented.T)
            .WithPipeline(p => p.UseLogging())
            .WithTransport(b => b.UseHttpServerSentEvents())
            .Handle(new(message.CounterName, newValue, message.IncrementBy), cancellationToken);

        return new CounterIncrementedResponse(
            await repository.GetCounterValue(message.CounterName)
        );
    }
}
